export const UPDATE_HUE_OFFSETX = 'UPDATE_HUE_OFFSETX'

export const UPDATE_HUE_RGB = 'UPDATE_HUE_RGB'

export const UPDATE_OPACITY_OFFSETX = 'UPDATE_OPACITY_OFFSETX'

export const UPDATE_OPACITY_VALUE = 'UPDATE_OPACITY_VALUE'

export const CHANGE_VALUES_TYPE = 'CHANGE_VALUES_TYPE'

export const UPDATE_SATURATION_POSITION = 'UPDATE_SATURATION_POSITION'

export const UPDATE_SATURATION_HSV = 'UPDATE_SATURATION_HSV'

export const UPDATE_SLIDER_WIDTH = 'UPDATE_SLIDER_WIDTH'

export const CACULATE_RGB = 'CACULATE_RGB'

export const CACULATE_HSL = 'CACULATE_HSL'

export const CACULATE_HEX = 'CACULATE_HEX'