export const UPDATE_HUE_OFFSETX = 'UPDATE_HUE_OFFSETX'

export const UPDATE_OPACITY_OFFSETX = 'UPDATE_OPACITY_OFFSETX'

export const CHANGE_VALUES_TYPE = 'CHANGE_VALUES_TYPE'

export const UPDATE_SATURATION_POSITION = 'UPDATE_SATURATION_POSITION'